### ISSUE TITLE
Testing  `Point` gives very thick points?

### ISSUE THREAD

**Issue by axkr** [Mathics3/mathics-threejs-backend#10]
I'm just testing `Point` and it gives very thick points:

![image](https://user-images.githubusercontent.com/3109793/128070150-566a60bb-8dcb-47f3-b3f4-790a5375f693.png)

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC
  "-//W3C//DTD XHTML 1.1 plus MathML 2.0 plus SVG 1.1//EN"
  "http://www.w3.org/2002/04/xhtml-math-svg/xhtml-math-svg.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" style="width: 100%; height: 100%; margin: 0; padding: 0">
<head>
<meta charset="utf-8">
<title>Graphics3D</title>
<script src="/media/js/mathics-threejs-backend.js"></script>
</head>

<body>
    <main id="graphics3d"></main>

    <script type="module"> 
        drawGraphics3d(
            document.getElementById('graphics3d'),
            {
                axes: {},
                elements: [{type: 'point',color: [0.5, 0.5, 0.5],coords: [[[0.0,0.0,1.0],null],[[0.628319,0.587785,0.809017],null],[[1.25664,0.951057,0.309017],null],[[1.88496,0.951057,-0.309017],null],[[2.51327,0.587785,-0.809017],null],[[3.14159,0.0,-1.0],null],[[3.76991,-0.587785,-0.809017],null],[[4.39823,-0.951057,-0.309017],null],[[5.02655,-0.951057,0.309017],null],[[5.65487,-0.587785,0.809017],null],[[6.28319,0.0,1.0],null]],pointSize: 1}],
                lighting: [
                    {
                        type: 'ambient',
                        color: [1, 1, 1]
                    }
                ],
                viewpoint: [2, -4, 4]
            }
        );
    </script>
</body>
```

**Comment by axkr** [comment]
BTW: the file from github cannot directly be used. Can you provide a real CDN?

![image](https://user-images.githubusercontent.com/3109793/128071148-aac116c8-c286-474c-b34c-bd9e32e8909e.png)

**Comment by TiagoCavalcanteTrindade** [comment]
@axkr I guess that the size of the points is different in Mathics and Symja. As the point size is half of the canvas size means that a point with `pointSize: 1` will have `canvasSize / 2` pixels of width.

**Comment by TiagoCavalcanteTrindade** [comment]
> BTW: the file from github cannot directly be used. Can you provide a real CDN?

Ok, I'll add it.

**Comment by rocky** [comment]
> > BTW: the file from github cannot directly be used. Can you provide a real CDN?
> 
> Ok, I'll add it.

We shouldn't do this in the git space - that is really for git.  

A suggestion might be to add this as a file under https://github.com/Mathics3/mathics-threejs-backend/releases which is a space that is intended and I guess scaled for downloads.

**Comment by TiagoCavalcanteTrindade** [comment]
> When I tried setting pointSize explicitly, I wasn't seeing it respected:

Maybe 0.01 is too small, for me, it's working.

**Comment by rocky** [comment]
My mystake. I now see that in the example and in the input pointSize was set to 1. In my example I set it to 0.01 earlier as well.

**Comment by axkr** [comment]
> We shouldn't do this in the git space - that is really for git.
> 
> A suggestion might be to add this as a file under https://github.com/Mathics3/mathics-threejs-backend/releases which is a space that is intended and I guess scaled for downloads.

with a cdn I meant a CDN  provider like for example jsdelivr.com:
- https://www.jsdelivr.com/?docs=gh

**Comment by rocky** [comment]
Ok - thanks for the clarification. I know very little about this. (And hope not to be involved with it.)

**Comment by axkr** [comment]
> Maybe 0.01 is too small, for me, it's working.

`0.03`gives the best result I think:
![image](https://user-images.githubusercontent.com/3109793/128088834-faf46e63-4199-4cec-ab1c-16561acbe1b7.png)

**Comment by TiagoCavalcanteTrindade** [comment]
> `0.03` gives the best result I think:

Good to know. About the CDN, I changed it in the [wiki](https://github.com/Mathics3/mathics-threejs-backend/wiki).
