### ISSUE TITLE
3D Spiral

### ISSUE THREAD

**Issue by lonnietc** [Mathics3/mathics-threejs-backend#104]
Hi All,

I am back to investigating Mathics as I have always thought that it had awesome potential.

I just came across the 

https://mathics3.github.io/mathics-threejs-backend/
and
https://mathics3.github.io/mathics-threejs-backend/examples

but did not see any example to draw a 3D spiral with number points or anything similar.

could you please help?

Thanks

**Comment by TiagoCavalcante** [comment]
@lonnietc do you want to draw something like [this](https://demonstrations.wolfram.com/PointsOnA3DSpiral/)? (or a filled spiral?)

Also, you want it to be in JavaScript or Mathics code?

**Comment by TiagoCavalcante** [comment]
I'm closing this due to lack of response
