### ISSUE TITLE
How does lighting with colors work?

### ISSUE THREAD

**Issue by axkr** [Mathics3/mathics-threejs-backend#15]
Must I inherit the color from lighting settings to all elements like in this example?

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC
  "-//W3C//DTD XHTML 1.1 plus MathML 2.0 plus SVG 1.1//EN"
  "http://www.w3.org/2002/04/xhtml-math-svg/xhtml-math-svg.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" style="width: 100%; height: 100%; margin: 0; padding: 0">
<head>
<meta charset="utf-8">
<title>Graphics3D</title>
<script src="https://cdn.jsdelivr.net/npm/@mathicsorg/mathics-threejs-backend@latest/bundle/index.js"></script>
</head>

<body>
    <main id="graphics3d"></main>

    <script type="module"> 
        drawGraphics3d(
            document.getElementById('graphics3d'),{
axes: {},
elements: [{type: 'sphere',color: [1.0,0.5,0.0],opacity: 0.5,radius: 1,coords: [[[0.0,0.0,0.0],null]]},
{type: 'cuboid',color: [1.0,0.5,0.0],opacity: 0.5,coords: [[[1.0,2.0,-1.0],null],[[2.0,3.0,1.0],null]]},
{type: 'cylinder',color: [1.0,0.5,0.0],opacity:  0.5,coords: [[[3.0,-1.0,0.0],null],[[3.0,-1.0,1.0],null]]}],
lighting: [{type: 'ambient',color: [1.0,0.5,0.0]}],
viewpoint: [2,-4,4]});
    </script>
</body>
```

BTW: you can activate "Discussion" in the Github project settings, so that questions are separated from real issues.

**Comment by rocky** [comment]
> BTW: you can activate "Discussion" in the Github project settings, so that questions are separated from real issues.

I don't see a setting for that. A link to instructions for how to set?

**Comment by TiagoCavalcanteTrindade** [comment]
> BTW: you can activate "Discussion" in the Github project settings, so that questions are separated from real issues.

It is activated now.

> Must I inherit the color from lighting settings to all elements like in this example?

The color seen by the user is a "merge" of the light's color and the primitives' color (with some exceptions like **line**). For example, if the primitive's light is white and the scene has a yellow ambient light, the color seen is going to be yellow.

**Comment by axkr** [comment]
Ok, how would you set the "default colors" for objects in the example in the "scope" section:

https://reference.wolfram.com/language/ref/Lighting.html
```
Graphics3D[{Sphere[], Cuboid[{1, 2, -1}, {2, 3, 1}], 
  Cylinder[{{3, -1, 0}, {3, -1, 1}}]}, 
 Lighting -> {{"Ambient", Orange}}]
```

**Comment by TiagoCavalcanteTrindade** [comment]
I'd set white.

**Comment by axkr** [comment]
Looks good now. Only difference is that cuboid and cylinder have frame lines in the original.

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC
  "-//W3C//DTD XHTML 1.1 plus MathML 2.0 plus SVG 1.1//EN"
  "http://www.w3.org/2002/04/xhtml-math-svg/xhtml-math-svg.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" style="width: 100%; height: 100%; margin: 0; padding: 0">
<head>
<meta charset="utf-8">
<title>Graphics3D</title>
<script src="https://cdn.jsdelivr.net/npm/@mathicsorg/mathics-threejs-backend@latest/bundle/index.js"></script>
</head>

<body>
    <main id="graphics3d"></main>

    <script type="module"> 
        drawGraphics3d(
            document.getElementById('graphics3d'),{
axes: {},
elements: [{type: 'sphere',color: [1.0, 1.0, 1.0],opacity: 1.0,radius: 1,coords: [[[0.0,0.0,0.0],null]]},{type: 'cuboid',color: [1.0, 1.0, 1.0],opacity: 1.0,coords: [[[1.0,2.0,-1.0],null],[[2.0,3.0,1.0],null]]},{type: 'cylinder',color: [1.0, 1.0, 1.0],opacity: 1.0,coords: [[[3.0,-1.0,0.0],null],[[3.0,-1.0,1.0],null]]}],
lighting: [{type: 'ambient',color: [1.0,0.5,0.0]}],
viewpoint: [2,-4,4]});
    </script>
</body>
```

**Comment by axkr** [comment]
> I don't see a setting for that. A link to instructions for how to set?

- https://docs.github.com/en/discussions/quickstart

**Comment by TiagoCavalcanteTrindade** [comment]
> Looks good now. Only difference is that cuboid and cylinder have frame lines in the original.

Could you send a print? They shouldn't have frame lines.

**Comment by axkr** [comment]
I think on screen display the Cuboid  and cylinder should have an "endge line" to have a better v 3D "feeling":

![image](https://user-images.githubusercontent.com/3109793/128567933-02707a05-61b3-4ff5-b2b4-95ec79307263.png)

**Comment by TiagoCavalcanteTrindade** [comment]
Adding a spot/directional light to the scene increases the 3d feeling.

```js
lighting: [
    {
        type: 'ambient',
        color: [0.5, 0.25, 0]
    },
    {
        type: 'directional',
        color: [1, 0.5, 0],
        coords: [null, [1,1,1]]
    }
]
```
![image](https://user-images.githubusercontent.com/62714153/128568607-6d2ff322-4265-444b-9acd-ae37033b334c.png)

**Comment by axkr** [comment]
With my tools I can get this:

`Graphics3D[{Sphere[], Cuboid[{1, 2, -1}, {2, 3, 1}], Cylinder[{{3, -1, 0}, {3, -1, 1}}]}, Lighting -> {{"Directional", Orange,{1,1,1}}}]`

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC
  "-//W3C//DTD XHTML 1.1 plus MathML 2.0 plus SVG 1.1//EN"
  "http://www.w3.org/2002/04/xhtml-math-svg/xhtml-math-svg.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" style="width: 100%; height: 100%; margin: 0; padding: 0">
<head>
<meta charset="utf-8">
<title>Graphics3D</title>
<script src="https://cdn.jsdelivr.net/npm/@mathicsorg/mathics-threejs-backend@latest/bundle/index.js"></script>
</head>

<body>
    <main id="graphics3d"></main>

    <script type="module"> 
        drawGraphics3d(
            document.getElementById('graphics3d'),{
axes: {},
elements: [{type: 'sphere',color: [1.0, 1.0, 1.0],opacity: 1.0,radius: 1,coords: [[[0.0,0.0,0.0]]]},{type: 'cuboid',color: [1.0, 1.0, 1.0],opacity: 1.0,coords: [[[1.0,2.0,-1.0]],[[2.0,3.0,1.0]]]},{type: 'cylinder',color: [1.0, 1.0, 1.0],opacity: 1.0,coords: [[[3.0,-1.0,0.0]],[[3.0,-1.0,1.0]]]}],
lighting: [{type: 'directional',color: [1.0,0.5,0.0],coords: [[1,1,1]]}],
viewpoint: [2,-4,4]});
    </script>
</body>
```

![image](https://user-images.githubusercontent.com/3109793/128569299-a19fb5e5-abdb-4c69-a27e-c2ff8d110c0d.png)

**Comment by rocky** [comment]
I think the final results of these should be added to the gallery as they are much nicer examples. 

I agree that in ambient lighting edge lines would be nice.  The spot light example, I think it helps to add the 6 spheres near the edges so that people can see the spotlight effect.

**Comment by TiagoCavalcanteTrindade** [comment]
> I agree that in ambient lighting edge lines would be nice.

The problem with it is that ambient light is a light from all points, which means no shadows, which means no visible edges. We could add an `EdgesGeometry` every time we add a cube, polyhedron, ..., but the result is not good to see, neither realist, neither performant.

**Comment by rocky** [comment]
The question as far as I am concerned is: what is the behavior of Mathematica? Because that is what we want to model. 

All the examples that I have seen so far for example https://reference.wolfram.com/language/ref/UniformPolyhedron.html seem to show edges distinct from faces. See for example the examples under the Details section. Faces in "Cube" seems to have be in light blue with maybe 50% some opacity, but the edges still seem white. 

There is some flexibility here, because we could have the front end overlay the image with its own edges as it seems to do for the outside box. 

There could be some sort of "speedy" option, but in the end should also recreate what you get in Mathematica.

**Comment by TiagoCavalcanteTrindade** [comment]
What about an option to set if the edges should be shown?

> All the examples that I have seen so far for example https://reference.wolfram.com/language/ref/UniformPolyhedron.html seem to show edges distinct from faces.

Yes, they do.

> There could be some sort of "speedy" option, but we should also be able to recreate what you get in Mathematica.
Yes, correct behavior is better than a faster but wrong one.
