### ISSUE TITLE
A green point for the light source is displayed

### ISSUE THREAD

**Issue by axkr** [Mathics3/mathics-threejs-backend#16]
At least with Firefox I see a green point for the light source, but only 4 objects should be displayed?

```
Graphics3D[{Sphere[], Sphere[{3, 0, 0}], Sphere[{0, 3, 0}],Sphere[{3, 3, 0}]}, Lighting -> {{"Point", Green, {2, 2, 2}}}]
```

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC
  "-//W3C//DTD XHTML 1.1 plus MathML 2.0 plus SVG 1.1//EN"
  "http://www.w3.org/2002/04/xhtml-math-svg/xhtml-math-svg.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" style="width: 100%; height: 100%; margin: 0; padding: 0">
<head>
<meta charset="utf-8">
<title>Graphics3D</title>
<script src="https://cdn.jsdelivr.net/npm/@mathicsorg/mathics-threejs-backend@latest/bundle/index.js"></script>
</head>

<body>
    <main id="graphics3d"></main>

    <script type="module"> 
        drawGraphics3d(
            document.getElementById('graphics3d'),{
axes: {},
elements: [{type: 'sphere',color: [1.0, 1.0, 1.0],opacity: 1.0,radius: 1,coords: [[[0.0,0.0,0.0],null]]},{type: 'sphere',color: [1.0, 1.0, 1.0],opacity: 1.0,radius: 1,coords: [[[3.0,0.0,0.0],null]]},{type: 'sphere',color: [1.0, 1.0, 1.0],opacity: 1.0,radius: 1,coords: [[[0.0,3.0,0.0],null]]},{type: 'sphere',color: [1.0, 1.0, 1.0],opacity: 1.0,radius: 1,coords: [[[3.0,3.0,0.0],null]]}],
lighting: [{type: 'point',color: [0.0,1.0,0.0],coords: [[2,2,2],null]}],
viewpoint: [2,-4,4]});
    </script>
</body>
```

![image](https://user-images.githubusercontent.com/3109793/128567379-dff25fff-5cab-4da0-947a-afc4a89dd629.png)

BTW: what is the `,null` at the end of the coords list needed for?

**Comment by TiagoCavalcanteTrindade** [comment]
> At least with Firefox I see a green point for the light source, but only 4 objects should be displayed?

No, the point light is visible. I have updated the [point light documentation](https://github.com/Mathics3/mathics-threejs-backend/wiki/lights-%E2%80%90-point).

**Comment by TiagoCavalcanteTrindade** [comment]
> BTW: what is the ,null at the end of the coords list needed for?

No.

**Comment by rocky** [comment]
Then why have it?

**Comment by TiagoCavalcanteTrindade** [comment]
> Then why have it?

It was there before, just kept it.

**Comment by TiagoCavalcanteTrindade** [comment]
It is removed now.

**Comment by TiagoCavalcanteTrindade** [comment]
@axkr is it solved?

**Comment by axkr** [comment]
Testing with: https://cdn.jsdelivr.net/npm/@mathicsorg/mathics-threejs-backend@latest/bundle/index.js 
the light source is printed.

**Comment by TiagoCavalcanteTrindade** [comment]
> Testing with: https://cdn.jsdelivr.net/npm/@mathicsorg/mathics-threejs-backend@latest/bundle/index.js
the light source is printed.

But wasn't it expected? A point light is a visible sphere.

**Comment by axkr** [comment]
Yes, see example on that page:

![image](https://user-images.githubusercontent.com/3109793/128809770-5221756e-20d3-44be-a004-ee56e285a86f.png)

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky maybe add an option `transparent`?

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade Sure - that is fine. But the default has to be True if we are to match MMA Graphics3D. 

@mmatera ?

I am not seeing an option to make the spot light visible.
