### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by TiagoCavalcanteTrindade** [Mathics3/mathics-threejs-backend#2]
@rocky and @mmatera I'd add tests, but it's a graphics library.

I searched a lot and I think the best way to do it is to test each primitive and light alone.  
Each test will have a threshold with a blurred image.

What are your thoughts?

**Comment by rocky** [comment]
Why not look to see how threejs does its testing and follow that?

**Comment by TiagoCavalcanteTrindade** [comment]
It does the same but without the blurring part, the problem with this is the following: three.js does a test in all its shaders, we just have one by primitive, if we change our shader, like disabling antialiasing the test is going to fail, if we replace lambert material by phong material, the test is going to fail.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky searching I found BackstopJS. It works in the following manner: you give a threshold, if the diff is smaller than the threshold the tests pass, otherwise, you can see the diff and approve it by yourself.

What do your think about using it instead of creating our own testing library?

**Comment by rocky** [comment]
Don't really have an opinion. But looking at the link it seems reasonable, so sure, try it!

**Comment by TiagoCavalcanteTrindade** [comment]
Ok, doing it.

**Comment by mmatera** [comment]
> @rocky searching I found [BackstopJS](https://github.com/garris/BackstopJS). It works in the following manner: you give a threshold, if the diff is smaller than the threshold the tests pass, otherwise, you can see the diff and approve it by yourself.
> 
> What do your think about using it instead of creating our own testing library?

Very cool!

**Comment by TiagoCavalcanteTrindade** [comment]
> Very cool!

Yes, creating the tests has been easy (and boring as we have various lights and primitives). I just need to create an HTML file with the `drawGraphics3d` call and add it to backstop.json.

**Comment by TiagoCavalcanteTrindade** [comment]
Done [here](d6b8b29b7bea7cad9367adbf9f93356f4ec4ed27).
