### ISSUE TITLE
Non 1:1 aspect ratio on Plot3D

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-threejs-backend#47]
Consider:

![plot3d](https://user-images.githubusercontent.com/8851/136716742-b17b9c1b-2bf3-4a22-9015-80e46d894245.png)

and compare with https://reference.wolfram.com/language/ref/Plot3D.html

Especially because of the low resolution, stretching points without adding more of them, makes the graininess more apparent. 

And I think that things that are not cube like should not be made to look cube like.

**Comment by TiagoCavalcante** [comment]
Mathics container 3.0.0 don't have this problem.

**Comment by rocky** [comment]
@TiagoCavalcante It looks like this problem goes back a ways and was right around and concurrent with the last mathics docker development interim update on Sept 12, 2021.

As best as I can tell there seem to be changes to both mathics-core as well as mathcis-threejs-backend that may need fixing. 

Here are details...

The mathics-latest docker image of Sept 12, 2021 is good. (sha256 1f25b214e91254876477cabe2445befde86e2c734328fb6836cbd03cdb516c61) 

So is the 4.4.0 release before that from Aug 1, 2021  sha256:4a10bb9c4fa56dc6942e6c763140a569c9ee6f18056dd3ef32082107705cfbc6

These both use mathics-backend-0.5.0. As soon as we get to 0.5.3, we start to see what is shown here. 

Commit [7219bca0276b07b4f8d6a52a79f0b2a289b4396f in mathics-core](https://github.com/Mathics3/mathics-core/commit/c1b73a82af173eb9a0015a4432cd37f486917098) is fine and will go with commit  [87357f5a5ba4151345a69361236f22ddb2b34d21 of mathics-django](https://github.com/Mathics3/mathics-django/commit/87357f5a5ba4151345a69361236f22ddb2b34d21). 

After that when 0.5.3 is introduces we start having problems.

**Comment by TiagoCavalcante** [comment]
I think that my test with 0.3.0 was wrong (probably Mathics Django didn't update the build file) as 0.5.0 is working.

**Comment by TiagoCavalcante** [comment]
Fixed in [mathics-core #71](https://github.com/Mathics3/mathics-core/pull/71).
