### ISSUE TITLE
Correctly check if a polygon is coplanar

### ISSUE THREAD

**Issue by TiagoCavalcante** [Mathics3/mathics-threejs-backend#48]
Currently, we are considering that a polygon is coplanar if all of its coordinates are parallel to an axis, this is wrong.

An option to do this the right way is do a [linear least squares and check if the distance of each point to the result plane is less than a threshold](https://math.stackexchange.com/questions/4336127/how-to-check-if-any-number-of-points-are-coplanar/4336140#4336140) (this was suggested by [mathcounterexamples.net](https://math.stackexchange.com/users/187663/mathcounterexamples-net)).

**Comment by rocky** [comment]
@TiagoCavalcante if we could get this in a release it will appear in both the Mathics-Django release and the possible mathics-omnibus release over the weekend.

**Comment by TiagoCavalcante** [comment]
@rocky it's done.
