### ISSUE TITLE
npm packaging warnings

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-threejs-backend#6]
Seen in CI buld log for Mathics-Django: 
```
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
npm install @mathicsorg/mathics-threejs-backend
##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
npm WARN mathics-django No repository field.
npm WARN mathics-django No license field.
```

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky it's a Mathics Django bug.

As Mathics Django isn't a JS library I didn't provide any information in its `package.json`, so npm warns against that, to solve it we just need to add those fields to Mathics Django's `package.json`.

**Comment by rocky** [comment]
What npm is warning against is a `package.json` file in its top-level directory messing with its packaging. 

Here we are using as purely JSON data -  Iihas nothing to do with npm packaging although it was created via npm.

 (Packaging is is done by Python here.)

In short I don't think it's a problem.  

If it helps, we could rename the file to something else like `graphics3d-info.json`.

**Comment by rocky** [comment]
Was as Mathics-Django issue and addressed there.
